"""Matching Agent — analyzes tasks and produces matching suggestions.

H2.3: dual-track — rule-based (default) + LLM-enhanced (opt-in).
LLM mode produces semantic matching brief. Falls back to rule-based on failure.
LLM NEVER makes accept/reject/seat-assignment decisions.
"""

import logging
import os
from typing import Any

from app.domain.a2a_protocol import AgentResult, DelegationContract, TaskEnvelope

logger = logging.getLogger(__name__)

AGENT_VERSION = "2.3.0"
LLM_ENABLED = os.getenv("MATCHING_LLM_ENABLED", "").lower() in ("true", "1", "yes")

MATCHING_SYSTEM_PROMPT = """\
You are a matching assistant for Twig Loop, a collaboration platform.

Your role: Generate a structured matching brief to help a human (founder/reviewer) \
evaluate whether a candidate fits a task.

CRITICAL RULES:
- You MUST NOT make accept/reject/hire decisions
- You MUST NOT claim skills or experience not stated in the input
- You MUST NOT assign seats or change application status
- You MUST clearly mark any inference or uncertainty
- You MUST stick to facts provided in the input
- Your output is advisory — the human makes all decisions

Output a JSON object with exactly these keys:
{
  "task_fit_summary": "Overall fit assessment between task and candidate profile",
  "strengths": ["List of matching strengths based on provided facts"],
  "gaps_and_risks": ["List of gaps, risks, or concerns"],
  "recommended_track": "formal_seat_candidate | growth_seat_candidate | needs_more_review",
  "explanation": "Natural language explanation for the founder/reviewer",
  "uncertainty_note": "What parts are inferred vs factual",
  "structured_signals": {
    "skill_overlap": "high | medium | low | unknown",
    "complexity_fit": "high | medium | low | unknown",
    "collaboration_fit": "high | medium | low | unknown"
  }
}"""


async def run_matching_agent(envelope: TaskEnvelope, contract: DelegationContract) -> AgentResult:
    """Produce matching suggestions. Uses LLM if enabled, falls back to rules."""
    rule_result = _build_rule_based_matching(envelope, contract)

    if not LLM_ENABLED:
        return rule_result

    llm_brief = await _try_llm_matching(envelope)
    if llm_brief is None:
        logger.info("LLM matching failed, using rule-based fallback")
        return rule_result

    return AgentResult(
        delegation_id=contract.delegation_id,
        result_type="matching_suggestion",
        summary=llm_brief.get("explanation", rule_result.summary),
        structured_payload={
            "brief_source": "llm",
            "task_fit_summary": llm_brief.get("task_fit_summary", ""),
            "strengths": llm_brief.get("strengths", []),
            "gaps_and_risks": llm_brief.get("gaps_and_risks", []),
            "recommended_track": llm_brief.get("recommended_track", "needs_more_review"),
            "explanation": llm_brief.get("explanation", ""),
            "uncertainty_note": llm_brief.get(
                "uncertainty_note",
                "This matching brief was generated by AI. Verify against actual candidate profile.",
            ),
            "structured_signals": llm_brief.get("structured_signals", {}),
            # Preserve rule-based metadata
            "recommended_seat_type": rule_result.structured_payload.get(
                "recommended_seat_type", ""
            ),
            "skill_requirements": rule_result.structured_payload.get("skill_requirements", []),
            "complexity_level": rule_result.structured_payload.get("complexity_level", ""),
        },
        confidence=0.7,
        requires_human_review=True,
        agent_version=AGENT_VERSION,
        trace_id=envelope.trace_id,
    )


async def _try_llm_matching(envelope: TaskEnvelope) -> dict[str, Any] | None:
    """Attempt LLM-enhanced matching. Returns None on any failure."""
    try:
        from app.services.agents.llm_client import generate_structured

        user_prompt = _build_llm_prompt(envelope)
        return await generate_structured(
            MATCHING_SYSTEM_PROMPT,
            user_prompt,
            agent_name="matching_agent",
            trace_id=envelope.trace_id,
            task_id=envelope.task_id,
        )
    except Exception:
        logger.exception("LLM matching generation error")
        return None


def _build_llm_prompt(envelope: TaskEnvelope) -> str:
    """Build user prompt from envelope data for matching."""
    parts = [
        f"Task objective: {envelope.objective}",
        f"Current status: {envelope.current_status}",
    ]

    if envelope.completion_criteria:
        parts.append(f"Completion criteria: {envelope.completion_criteria}")

    task_type = envelope.constraints.get("task_type", "")
    main_role = envelope.constraints.get("main_role", "")
    risk_level = envelope.constraints.get("risk_level", "")
    ewu = envelope.constraints.get("ewu", "")

    if task_type:
        parts.append(f"Task type: {task_type}")
    if main_role:
        parts.append(f"Required role: {main_role}")
    if risk_level:
        parts.append(f"Risk level: {risk_level}")
    if ewu:
        parts.append(f"Task EWU (effort): {ewu}")

    # Candidate context from signal_context
    signals = envelope.signal_context
    if signals.get("candidate_skills"):
        parts.append(f"Candidate skills: {signals['candidate_skills']}")
    if signals.get("candidate_experience"):
        parts.append(f"Candidate experience: {signals['candidate_experience']}")
    if signals.get("candidate_availability"):
        parts.append(f"Candidate availability: {signals['candidate_availability']}")
    if signals.get("application_note"):
        parts.append(f"Application note: {signals['application_note']}")

    return "\n".join(parts)


def _build_rule_based_matching(envelope: TaskEnvelope, contract: DelegationContract) -> AgentResult:
    """Original rule-based matching (always available as fallback)."""
    suggestions: list[str] = []

    task_type = envelope.constraints.get("task_type", "")
    main_role = envelope.constraints.get("main_role", "")
    try:
        ewu = float(envelope.constraints.get("ewu", 0))
    except (ValueError, TypeError):
        ewu = 0.0

    if task_type == "development":
        suggestions.append(f"This is a development task requiring a {main_role}.")
        if ewu >= 6:
            suggestions.append("High complexity (EWU >= 6) — recommend experienced developers.")
        else:
            suggestions.append("Moderate complexity — suitable for growth seat candidates.")
    elif task_type == "product_design":
        suggestions.append("Design task — look for candidates with design portfolio.")
    else:
        suggestions.append(f"Task type: {task_type} — match based on {main_role} skills.")

    if ewu >= 5:
        seat_suggestion = "formal"
        suggestions.append("Recommend formal seat for high-EWU task.")
    else:
        seat_suggestion = "growth"
        suggestions.append("Growth seat appropriate for this complexity level.")

    return AgentResult(
        delegation_id=contract.delegation_id,
        result_type="matching_suggestion",
        summary=" ".join(suggestions),
        structured_payload={
            "brief_source": "rule_based",
            "recommended_seat_type": seat_suggestion,
            "skill_requirements": [main_role, task_type],
            "complexity_level": "high" if ewu >= 6 else "moderate" if ewu >= 3 else "low",
            "matching_notes": suggestions,
        },
        confidence=0.7,
        requires_human_review=True,
        agent_version=AGENT_VERSION,
        trace_id=envelope.trace_id,
    )
