"""Review Prep Agent — prepares evidence review brief for reviewers.

H2.2: dual-track — rule-based (default) + LLM-enhanced (opt-in).
LLM mode produces structured semantic summary. Falls back to rule-based on failure.
LLM NEVER makes approve/reject decisions — only generates review brief.
"""

import logging
import os
from typing import Any

from app.domain.a2a_protocol import AgentResult, DelegationContract, TaskEnvelope

logger = logging.getLogger(__name__)

AGENT_VERSION = "2.2.0"
LLM_ENABLED = os.getenv("REVIEW_PREP_LLM_ENABLED", "").lower() in ("true", "1", "yes")

REVIEW_SYSTEM_PROMPT = """\
You are a review preparation assistant for Twig Loop.

Your role: Generate a structured review brief to help a human reviewer evaluate task completion.

CRITICAL RULES:
- You MUST NOT make approve/reject/pass/fail decisions
- You MUST NOT claim evidence exists if it is not in the input
- You MUST NOT treat GitHub signals as proof of completion
- You MUST clearly mark any inference or uncertainty
- You MUST stick to facts provided in the input
- Your output is advisory — the human reviewer makes all decisions

Output a JSON object with exactly these keys:
{
  "task_summary": "Brief summary of the task and its objective",
  "completion_criteria_analysis": "Summary of criteria and which appear covered vs unclear",
  "evidence_summary": "What evidence has been submitted, types, and coverage",
  "signal_summary": "GitHub signals status and what they indicate",
  "gaps_and_risks": ["List of gaps, risks, or items needing reviewer attention"],
  "reviewer_focus_areas": ["Specific areas the reviewer should examine closely"],
  "uncertainty_note": "What parts of this brief are inferred vs factual"
}"""


async def run_review_prep_agent(
    envelope: TaskEnvelope, contract: DelegationContract
) -> AgentResult:
    """Prepare a review brief. Uses LLM if enabled, falls back to rules."""
    # Always generate rule-based brief first (serves as fallback)
    rule_result = _build_rule_based_brief(envelope, contract)

    if not LLM_ENABLED:
        return rule_result

    # Try LLM enhancement
    llm_brief = await _try_llm_brief(envelope)
    if llm_brief is None:
        logger.info("LLM brief generation failed, using rule-based fallback")
        return rule_result

    # Merge: LLM sections + rule-based metadata
    return AgentResult(
        delegation_id=contract.delegation_id,
        result_type="review_brief",
        summary=llm_brief.get("task_summary", rule_result.summary),
        structured_payload={
            "brief_source": "llm",
            "task_summary": llm_brief.get("task_summary", ""),
            "completion_criteria_analysis": llm_brief.get("completion_criteria_analysis", ""),
            "evidence_summary": llm_brief.get("evidence_summary", ""),
            "signal_summary": llm_brief.get("signal_summary", ""),
            "gaps_and_risks": llm_brief.get("gaps_and_risks", []),
            "reviewer_focus_areas": llm_brief.get("reviewer_focus_areas", []),
            "uncertainty_note": llm_brief.get(
                "uncertainty_note",
                "This brief was generated by AI. Verify all claims against evidence.",
            ),
            # Preserve rule-based metadata for compatibility
            "review_checklist": rule_result.structured_payload.get("review_checklist", []),
            "evidence_count": rule_result.structured_payload.get("evidence_count", 0),
            "has_repo": rule_result.structured_payload.get("has_repo", False),
        },
        confidence=0.75,  # LLM brief has capped confidence
        requires_human_review=True,
        agent_version=AGENT_VERSION,
        trace_id=envelope.trace_id,
    )


async def _try_llm_brief(envelope: TaskEnvelope) -> dict[str, Any] | None:
    """Attempt to generate LLM-enhanced brief. Returns None on any failure."""
    try:
        from app.services.agents.llm_client import generate_structured

        user_prompt = _build_llm_prompt(envelope)
        return await generate_structured(
            REVIEW_SYSTEM_PROMPT,
            user_prompt,
            agent_name="review_prep_agent",
            trace_id=envelope.trace_id,
            task_id=envelope.task_id,
        )
    except Exception:
        logger.exception("LLM brief generation error")
        return None


def _build_llm_prompt(envelope: TaskEnvelope) -> str:
    """Build the user prompt from envelope data."""
    signals = envelope.signal_context
    parts = [
        f"Task objective: {envelope.objective}",
        f"Current status: {envelope.current_status}",
        f"Completion criteria: {envelope.completion_criteria}",
    ]

    if envelope.evidence_requirements:
        parts.append(f"Required evidence types: {', '.join(envelope.evidence_requirements)}")

    evidence_count = signals.get("evidence_count", 0)
    parts.append(f"Evidence submitted: {evidence_count} items")

    if signals.get("repo_url"):
        parts.append(f"Repository: {signals['repo_url']}")
    if signals.get("pr_url"):
        parts.append(f"Pull request: {signals['pr_url']}")
    if signals.get("pr_lifecycle"):
        pr_lc = signals["pr_lifecycle"]
        parts.append(f"PR status: {pr_lc.get('pr_status', 'unknown')}")
    if signals.get("signal_status"):
        parts.append(f"Signal quality: {signals['signal_status']}")

    ewu = signals.get("ewu", "")
    if ewu:
        parts.append(f"Task EWU (effort): {ewu}")

    return "\n".join(parts)


def _build_rule_based_brief(envelope: TaskEnvelope, contract: DelegationContract) -> AgentResult:
    """Original rule-based brief generation (always available as fallback)."""
    evidence_reqs = envelope.evidence_requirements
    criteria = envelope.completion_criteria
    signals = envelope.signal_context

    brief_items: list[str] = []
    brief_items.append(f"Task objective: {envelope.objective}")

    if criteria:
        brief_items.append(f"Completion criteria: {criteria}")

    if evidence_reqs:
        brief_items.append(f"Required evidence types: {', '.join(evidence_reqs)}")
    else:
        brief_items.append("No specific evidence type requirements defined.")

    if signals.get("evidence_count", 0) > 0:
        brief_items.append(f"Evidence submitted: {signals['evidence_count']} items")
    else:
        brief_items.append("No evidence submitted yet.")

    if signals.get("repo_url"):
        brief_items.append(f"Repository: {signals['repo_url']}")

    checklist = [
        "Verify evidence URLs are accessible",
        "Check if deliverables match output_spec",
        "Confirm completion_criteria are met",
        "Assess if evidence is sufficient for EWU claim",
    ]

    return AgentResult(
        delegation_id=contract.delegation_id,
        result_type="review_brief",
        summary="\n".join(brief_items),
        structured_payload={
            "brief_source": "rule_based",
            "review_brief": brief_items,
            "review_checklist": checklist,
            "evidence_count": signals.get("evidence_count", 0),
            "has_repo": bool(signals.get("repo_url")),
            "recommendation": (
                "Review evidence before approving"
                if signals.get("evidence_count", 0) > 0
                else "Wait for evidence submission"
            ),
        },
        confidence=0.6,
        requires_human_review=True,
        agent_version=AGENT_VERSION,
        trace_id=envelope.trace_id,
    )
